function aircraft_states = aircraftLoadMdlStates(model_name,aircraft_block_name)
% aircraftLoadMdStates description of states in the aircraft library blocks

aircraft_states.Continuous = [];
aircraft_states.Discrete = [];

switch aircraft_block_name
    case 'Rigid aircraft with steady aerodynamics'
        wing_name_prefix 	= 'wing vlm rigid steady';
        aircraft_states.Continuous = ...
            [ ...
            loadRigidBodyStates(model_name,aircraft_block_name,0); ...
            loadSteadyAeroContStates(model_name,aircraft_block_name); ...
            loadActuatorStates(model_name,aircraft_block_name); ...
            ];
        aircraft_states.Discrete = ...
            [ ...
            loadSteadyAeroDiscStates(model_name,aircraft_block_name,wing_name_prefix); ...
            ];
    case 'Rigid aircraft with unsteady aerodynamics'
        wing_name_prefix 	= 'wing vlm rigid unsteady';
        fuse_name_suffix    = 'rigid unsteady';
        aircraft_states.Continuous = ...
            [ ...
            loadRigidBodyStates(model_name,aircraft_block_name,0); ...
            loadUnstAeroContStates(model_name,aircraft_block_name,wing_name_prefix,fuse_name_suffix); ...
            loadActuatorStates(model_name,aircraft_block_name); ...
            ];
        aircraft_states.Discrete = ...
            [ ...
            % loadUnstAeroDiscStates(model_name,aircraft_block_name,wing_name_prefix); ...
            ];
    case 'Flexible aircraft with steady aerodynamics'
        wing_name_prefix 	= 'wing vlm flexible steady';
        aircraft_states.Continuous = ...
            [ ...
            loadRigidBodyStates(model_name,aircraft_block_name,1); ...
            loadStructureStates(model_name,aircraft_block_name); ...
            loadSteadyAeroContStates(model_name,aircraft_block_name); ...
            loadActuatorStates(model_name,aircraft_block_name); ...
            ];
        aircraft_states.Discrete = ...
            [ ...
            loadSteadyAeroDiscStates(model_name,aircraft_block_name,wing_name_prefix); ...
            ];
    case 'Flexible aircraft with unsteady aerodynamics'
        wing_name_prefix 	= 'wing vlm aeroelastic';
        fuse_name_suffix    = 'aeroelastic';
        aircraft_states.Continuous = ...
            [ ...
            loadRigidBodyStates(model_name,aircraft_block_name,1); ...
            loadUnstAeroContStates(model_name,aircraft_block_name,wing_name_prefix,fuse_name_suffix); ...
            loadStructureStates(model_name,aircraft_block_name); ...
            loadActuatorStates(model_name,aircraft_block_name); ...
            ];
        aircraft_states.Discrete = ...
            [ ...
            loadUnstAeroDiscStates(model_name,aircraft_block_name,wing_name_prefix); ...
            ];
    otherwise
        warning('Could not find valid aircraft model.');
end





function rigid_body_states = loadRigidBodyStates(model_name,aircraft_block_name,is_flexible)
        
    if is_flexible
        sub_block_name = ['/flexible body equations of motion',newline,'(simple)/Rigid body kinematics/'];
        V_Kb = 'V_Kb';
    else
        sub_block_name = ['/State equations',newline,'(Quaternions)',newline,'w// non-constant g/'];
        V_Kb = 'V__Kb';
    end
    
    rigid_body_states = ...
        { ...
        {'qt_0'; 'qt_1'; 'qt_2'; 'qt_3'} ,...
                             '-',    ''    ,'Quaternions'                ,[ model_name, '/', aircraft_block_name, sub_block_name, 'q_bg'];...
        {'u_Kb'; 'v_Kb'; 'w_Kb'},...
                            'm/s',   ''    ,'Body-frame velocities'      ,[ model_name, '/', aircraft_block_name, sub_block_name, V_Kb];...   
        {'x__g'; 'y__g'; 'z__g'},...
                            'm',     ''    ,'Earth-frame position'       ,[ model_name, '/', aircraft_block_name, sub_block_name, 's__g'];...         
        {'p_Kb'; 'q_Kb'; 'r_Kb'},...
                            'rad/s', ''    ,'Angular rates'              ,[ model_name, '/', aircraft_block_name, sub_block_name, 'rates'];...   
        };
end

function unst_aero_states = loadUnstAeroContStates(model_name,aircraft_block_name,wingNamePrefix,fuse_name_suffix)
        
    unst_aero_states = ...
        { ...
        'x_aero_wing'     , '-',   ''    ,'Unsteady aerodynamic state - main wing'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - main wing/Integrator'];...
        'X_wing'          , '-',   ''    ,'Dynamic stall state - main wing'            ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - main wing/Integrator1'];...
        'flap_aero_wing'  , '-',   ''    ,'Unsteady aerodynamic state - main wing'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - main wing/Integrator2'];...
        'act_aero_wing'   , '-',   ''    ,'Unsteady aerodynamic state - main wing'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - main wing/Integrator3'];...
        'tau_v_wing'      , '-',   ''    ,'Dimensionless time of leading edge vortex - main wing'   ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - main wing/Integrator4'];...
        'alpha_ind_wing'  , '-',   ''    ,'Induced angle of attack - main wing'        ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - main wing/T1 delay/Integrator5'];...

        'x_aero_htp'     , '-',   ''    ,'Unsteady aerodynamic state - HTP'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - htp/Integrator'];...
        'X_htp'          , '-',   ''    ,'Dynamic stall state - HTP'            ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - htp/Integrator1'];...
        'flap_aero_htp'  , '-',   ''    ,'Unsteady aerodynamic state - HTP'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - htp/Integrator2'];...
        'act_aero_htp'   , '-',   ''    ,'Unsteady aerodynamic state - HTP'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - htp/Integrator3'];...
        'tau_v_htp'      , '-',   ''    ,'Dimensionless time of leading edge vortex - HTP'   ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - htp/Integrator4'];...
        'alpha_ind_htp'  , '-',   ''    ,'Induced angle of attack - HTP'        ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - htp/T1 delay/Integrator5'];...

        'x_aero_vtp'     , '-',   ''    ,'Unsteady aerodynamic state - VTP'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - vtp/Integrator'];...
        'X_vtp'          , '-',   ''    ,'Dynamic stall state - VTP'            ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - vtp/Integrator1'];...
        'flap_aero_vtp'  , '-',   ''    ,'Unsteady aerodynamic state - VTP'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - vtp/Integrator2'];...
        'act_aero_vtp'   , '-',   ''    ,'Unsteady aerodynamic state - VTP'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - vtp/Integrator3'];...
        'tau_v_vtp'      , '-',   ''    ,'Dimensionless time of leading edge vortex - VTP'   ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - vtp/Integrator4'];...
        'alpha_ind_vtp'  , '-',   ''    ,'Induced angle of attack - VTP'        ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - vtp/T1 delay/Integrator5'];...

        'R_Ab_fus'      , '-',   ''    ,'Unsteady segment forces - fuselage'  ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/fuselage ', fuse_name_suffix,'/Integrator'];...

        'x_downwash'     , '-',   ''    ,'Unsteady downwash state'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/unsteady downwash/Transfer function (continuous)/Integrator'];...
        'delay_downwash', '-',   ''   ,'Delayed unsteady downwash'              ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/unsteady downwash/Variable Transport Delay'];...
        };
end

function cont_unst_aero_states = loadUnstAeroDiscStates(model_name,aircraft_block_name,wingNamePrefix)
    % to do: the leading edge shock could be removed from the models
    cont_unst_aero_states = ...
        { ...
        'is_le_shock_wing'     , '-',   ''    ,'Leading edge shock indicator - main wing'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - main wing/Unit Delay2'];...
        'is_le_shock_htp'          , '-',   ''    ,'Leading edge shock indicator - main wing'            ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - main wing/Unit Delay2'];...
        'is_le_shock_vtp'  , '-',   ''    ,'Leading edge shock indicator - main wing'     ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - main wing/Unit Delay2'];...
        };
end

function cont_steady_aero_states = loadSteadyAeroContStates(model_name,aircraft_block_name)
    cont_steady_aero_states = ...
        { ...
        'delay_downwash', '-',   ''   ,'Delayed unsteady downwash'              ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/static downwash/Variable Transport Delay'];...
        };
end

function disc_steady_aero_states = loadSteadyAeroDiscStates(model_name,aircraft_block_name,wingNamePrefix)
    % These are discrete states
    disc_steady_aero_states = ...
        { ...
        'alpha_ind_wing'  , '-',   ''    ,'Induced angle of attack - main wing'        ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - main wing/Unit Delay1'];...
        'alpha_ind_htp'  , '-',   ''    ,'Induced angle of attack - HTP'        ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - htp/Unit Delay1'];...
        'alpha_ind_vtp'  , '-',   ''    ,'Induced angle of attack - VTP'        ,[ model_name, '/', aircraft_block_name, '/Aerodynamics/',wingNamePrefix,' - vtp/Unit Delay1'];...
        };
end

function structure_states = loadStructureStates(model_name,aircraft_block_name)
    
    structure_states = ...
        { ...
        'eta'             , '-',     ''    ,'Flex. mode gen. coord.'     ,[ model_name, '/', aircraft_block_name, '/flexible body equations of motion',newline,'(simple)/free vibrations integration/Integrator1'];...   
        'eta_dt'          , '-/s',   ''    ,'Flex. mode rate'            ,[ model_name, '/', aircraft_block_name, '/flexible body equations of motion',newline,'(simple)/free vibrations integration/Integrator'];...  
        };
end

function actuator_states = loadActuatorStates(model_name,aircraft_block_name)

    actuator_states = ...
        { ...
        'da'              , 'rad',   ''    ,'Aileron deflection'         ,[ model_name, '/', aircraft_block_name, '/commands 2 actuators/Nonlinear Second-Order Actuator aileron/A'];...   
        'dLAD'            , '-',     ''    ,'LAD position'               ,[ model_name, '/', aircraft_block_name, '/commands 2 actuators/LAD dynamics/Integrator'];...   
        'de'              , 'rad',   ''    ,'Elevator deflection'        ,[ model_name, '/', aircraft_block_name, '/commands 2 actuators/Nonlinear Second-Order Actuator elevator/A'];...   
        'dr'              , 'rad',   ''    ,'Rudder deflection'          ,[ model_name, '/', aircraft_block_name, '/commands 2 actuators/Nonlinear Second-Order Actuator rudder/A'];...   
        'thrust'              , 'N',   ''    ,'Total thrust'          ,[ model_name, '/', aircraft_block_name, '/commands 2 actuators/thrust dynamics/Integrator'];...   
        'dHTP'              , 'rad',   ''    ,'HTP deflection'          ,[ model_name, '/', aircraft_block_name, '/commands 2 actuators/Nonlinear Second-Order Actuator htp/A'];...   
        
        'da_dt'           , 'rad/s', ''    ,'Aileron deflection rate'    ,[ model_name, '/', aircraft_block_name, '/commands 2 actuators/Nonlinear Second-Order Actuator aileron/dot_A'];...   
        'de_dt'           , 'rad/s', ''    ,'Elevator deflection rate'   ,[ model_name, '/', aircraft_block_name, '/commands 2 actuators/Nonlinear Second-Order Actuator elevator/dot_A'];...   
        'dr_dt'           , 'rad/s', ''    ,'Rudder deflection rate'     ,[ model_name, '/', aircraft_block_name, '/commands 2 actuators/Nonlinear Second-Order Actuator rudder/dot_A'];...  
        'dHTP_dt'           , 'rad/s', ''    ,'HTP deflection rate'     ,[ model_name, '/', aircraft_block_name, '/commands 2 actuators/Nonlinear Second-Order Actuator htp/dot_A'];...  
        };
end


end

