function envir_states = envirLoadMdlStates(model_name,envir_block_name)

envir_states.Continuous = [];
envir_states.Discrete = [];

switch envir_block_name
    case ['Environment',newline,'with successive 1-cos gusts']
        envir_states.Continuous = ...
            { ...
            't_first_gust'    , 's',     ''    ,'Countdown to first gust'    ,[ model_name, '/', envir_block_name,'/1-cos gust generator/Integrator1'];...   
            't_gust'          , 's',     ''    ,'Gust penetration time'      ,[ model_name, '/', envir_block_name,'/1-cos gust generator/delta_time'];... 
            's_gust'          , 'm',     ''    ,'Gust penetration distance'  ,[ model_name, '/', envir_block_name,'/1-cos gust generator/Integrator'];...   
            };
        envir_states.Discrete = ...
            { ...
            'gustGradDist_old' , 'm',      ''      ,'Previous gust gradient'  ,[ model_name ,'/', envir_block_name,'/1-cos gust generator/Delay'];...
            'b_nextGust_1'     , '',       ''      ,'Bool. next gust'    ,[ model_name ,'/', envir_block_name,'/1-cos gust generator/Unit Delay2'];...
            'b_gustOver'       , '',       ''      ,'Bool. end of gust'  ,[ model_name ,'/', envir_block_name,'/1-cos gust generator/Unit Delay1'];...
            'b_nextGust_2'     , '',       ''      ,'Bool. next gust'    ,[ model_name ,'/', envir_block_name,'/1-cos gust generator/Unit Delay3'];...
            'V_wg_dt'          , '',    ''      ,'Discrete derivative of V_Wg'   ,[ model_name ,'/', envir_block_name,'/Discrete Derivative/UD'];...
            };
        
    case ['Environment',newline,'with single 1-cos gusts']
        envir_states.Continuous = ...
            { ...
            't_first_gust'    , 's',     ''    ,'Countdown to first gust'    ,[ model_name, '/', envir_block_name,'/1-cos gust generator/Integrator1'];...   
            't_gust'          , 's',     ''    ,'Gust penetration time'      ,[ model_name, '/', envir_block_name,'/1-cos gust generator/delta_time'];... 
            's_gust'          , 'm',     ''    ,'Gust penetration distance'  ,[ model_name, '/', envir_block_name,'/1-cos gust generator/Integrator'];...   
            };
        envir_states.Discrete = ...
            { ...
            'gustGradDist_old' , 'm',      ''      ,'Previous gust gradient'  ,[ model_name ,'/', envir_block_name,'/1-cos gust generator/Delay'];...
            'b_nextGust_1'     , '',       ''      ,'Bool. next gust'    ,[ model_name ,'/', envir_block_name,'/1-cos gust generator/Unit Delay2'];...
            'b_gustOver'       , '',       ''      ,'Bool. end of gust'  ,[ model_name ,'/', envir_block_name,'/1-cos gust generator/Unit Delay1'];...
            'b_nextGust_2'     , '',       ''      ,'Bool. next gust'    ,[ model_name ,'/', envir_block_name,'/1-cos gust generator/Unit Delay3'];...
            'V_wg_dt'          , '',    ''      ,'Discrete derivative of V_Wg'   ,[ model_name ,'/', envir_block_name,'/Discrete Derivative/UD'];...
            };
    case ['Environment',newline,'with single external wind input']; ...
        envir_states.Continuous = ...
            { ...
            };
        envir_states.Discrete = ...
            { ...
            'V_wg_dt'          , '',    ''      ,'Discrete derivative of V_Wg'   ,[ model_name ,'/', envir_block_name,'/Discrete Derivative/UD'];...
            };
    case ['Environment',newline,'with single external wind input linear']; ...
        envir_states.Continuous = ...
            { ...
            };
        envir_states.Discrete = ...
            { ...
            'V_wg_dt'          , '',    ''      ,'Discrete derivative of V_Wg'   ,[ model_name ,'/', envir_block_name,'/Discrete Derivative/UD'];...
            };
        
    case ['Environment',newline,'with zonal external wind input linear']; ...
        envir_states.Continuous = ...
            { ...
            'x_chain_w_wing'    , '',    ''    ,'Chain delays from gust interaction model'    ,[ model_name, '/', envir_block_name,'/wind at wings linear vertical zones/Delays_w_wing'];...
            'x_chain_w_dt_wing' , '',    ''    ,'Chain delays from gust interaction model'    ,[ model_name, '/', envir_block_name,'/wind at wings linear vertical zones/Delays_w_dt_wing'];...
            'x_chain_w_htp'     , '',    ''    ,'Chain delays from gust interaction model'    ,[ model_name, '/', envir_block_name,'/wind at wings linear vertical zones/Delays_w_htp'];...
            'x_chain_w_dt_htp'  , '',    ''    ,'Chain delays from gust interaction model'    ,[ model_name, '/', envir_block_name,'/wind at wings linear vertical zones/Delays_w_dt_htp'];...
            'x_chain_w_vtp'     , '',    ''    ,'Chain delays from gust interaction model'    ,[ model_name, '/', envir_block_name,'/wind at wings linear vertical zones/Delays_w_vtp'];...
            'x_chain_w_dt_vtp'  , '',    ''    ,'Chain delays from gust interaction model'    ,[ model_name, '/', envir_block_name,'/wind at wings linear vertical zones/Delays_w_dt_vtp'];...
            'x_chain_w_fus'     , '',    ''    ,'Chain delays from gust interaction model'    ,[ model_name, '/', envir_block_name,'/wind at wings linear vertical zones/Delays_w_fus'];...
            'x_filt_w'          , '',    ''    ,'Wind filter states'                          ,[ model_name, '/', envir_block_name,'/wind filter/Filter w/Integrator'];...
            };
        envir_states.Discrete = ...
            { ...
            };
        
end
        
end
